rileyleee/GoodNews

GoodNews/app/src/main/java/com/saveurlife/goodnews/enterinfo/EnterInfoActivity.kt
GoodNews/gradle.properties

1. back-end 의 성별 한자리 규칙에 따라서 app 전송 코드 변경
2. 나머지 기본 값 변경

fix: default value 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/enterinfo/EnterInfoActivity.kt
GoodNews/gradle.properties

1. be의 성별 한자리 수 규칙에 따라 app 코드 변경
2. 기본 값 변경

fix: enterinfo 기본 값 변경

---

BE-WEB/member/src/main/java/com/goodnews/member/member/domain/FacilityState.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/response/family/FamilyPlaceInfoResponseDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/service/FacilityService.java
BE-WEB/member/src/main/java/com/goodnews/member/member/service/FamilyService.java

fix: db형식 수정

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/LoadingActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/MemberAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/enterinfo/EnterInfoActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/main/MainActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/main/MyStatusFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/mypage/MyPageFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/AllDataSync.kt

변경사항
1. 마이페이지 기본값 및 나이 설정 수정
2. 오프라인 가입 시 서버 등록 수정
3. 동기화 비동기 수정
추가 변경 필요 사항
1. 페이지 엄청엄청 빠르게 넘길때 생기는 문제 수정 필요
2. 수정 시간 확인 필요

fix: 마이페이지 관련 동기화 수정

---

FE-WEB/good-news/src/components/@common/Footer.tsx
FE-WEB/good-news/src/components/home/SubIntro2.tsx

design: 크기 및 주석 처리
- 웹 텍스트 크기 및 불필요 코드 주석 처리

design: 크기 및 주석 처리

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyPlaceAddEditFragment.kt

feat: 토글 버튼 수정

---

BE-WEB/map/src/main/resources/application-prd.properties
BE-WEB/member/src/main/resources/application-prd.properties

수정 사항
- MySQL, MongoDB, Redis 연결 관련 정보 수정

hotfix : DB 연결 정보 수정

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/mypage/MyPageFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/tutorial/TutorialActivity.kt
GoodNews/app/src/main/res/layout/fragment_my_page.xml

**변경된 부분**
- 다크모드 및 내 위치 공개 여부 UI와 설정 변경
- 마이페이지의 다크모드 토글 버튼 주석처리
- MyPageFragment.kt 내 위치 공개하기 기능 기본 값 False
- 토글 버튼을 클릭했을 때 활성화가 되며, shared preference에 저장 (True)

feat: 다크모드 및 내 위치 공개 여부 UI, 설정 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/map/EmergencyInfoDialogFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/models/MapInstantInfo.kt

1. 위험 정보 데이터 동기화를 위한 id 컬럼 추가 
2. 위험 정보 등록 시 위경도를 소수점 셋째자리까지만 저장

fix: 위험정보 데이터 id 컬럼 추가 및 위경도 소수점 세자리로 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/GoodNewsApplication.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/DangerInfoRealmRepository.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/GroupRepository.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/advertise/AdvertiseManager.java
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/bleGattClient/BleGattCallback.java
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/message/AutoSendMessageService.java
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/message/SendMessageManager.java
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/service/BleService.java
GoodNews/app/src/main/java/com/saveurlife/goodnews/enterinfo/EnterInfoActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyAddFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/main/MyStatusDialogFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/BackgroundLocationProvider.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/EmergencyInfoDialogFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/mypage/MyPageFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/service/UserDeviceInfoService.java
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/AllDataSync.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSyncWorker.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/FamilySync.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/InitSyncWorker.kt

UserDeviceInfoService 가 앱 전체에서 엄청 많이 쓰이고 사용될 때마다 객체 생성돼서 싱글톤으로 바꿨는데 사용되는 곳이 되게 많아서 이로 인한 오류가 생기는지 확인해 주시죠 ㄟ( ▔, ▔ )ㄏ

Be/ble ble 코드 개선, 그룹 백 코드, 위치 공개 여부 반영, UserDeviceInfoService 싱글톤 적용

---

GoodNews/app/src/main/AndroidManifest.xml
GoodNews/app/src/main/java/com/saveurlife/goodnews/LoadingActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/MapAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/MapData.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/MemberAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/DangerInfoRealmRepository.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/enterinfo/EnterInfoActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/main/MyStatusFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/EmergencyAlarmProvider.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/EmergencyInfoDialogFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/FacilityListAdapter.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MapFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/mypage/MyPageFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/BatchData.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSync.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSyncWorker.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DeleteOldDataReciver.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/SyncService.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/TimeService.kt

- mapinstanceinfo sync로직 수정
- 오래된 데이터 삭제 로직 추가 (진행중)
- db 수정에 따른 retrofit 통신 로직 수정
- sync 파일 리팩토링

feat : sync 로직 수정

---

GoodNews/app/src/main/res/layout/activity_loading.xml
GoodNews/app/src/main/res/values-night/colors.xml

fix: 다크모드 death 속성 및 로딩페이지 수정

---

BE-WEB/member/src/main/resources/application-dev.properties
BE-WEB/member/src/main/resources/application.properties

TEST : port 변경

---

BE-WEB/member/src/main/resources/application-prd.properties

TEST:redis info

---

BE-WEB/member/src/main/resources/application-dev.properties
BE-WEB/member/src/main/resources/application-prd.properties

빌드 시 레디스 연결 오류로 인한 테스트
예상 원인 : redis 연결 시 prd 파일이 아닌 dev 파일을 읽는 것 같음..

test:redis

---

BE-WEB/map/src/main/resources/application-prd.properties

test : db connect info

---

BE-WEB/member/src/main/resources/application-prd.properties

test:db connect

---

BE-WEB/map/src/main/resources/application-prd.properties

test:map info test

---

BE-WEB/gateway/src/main/resources/application.yml
BE-WEB/member/src/main/resources/application-prd.properties

fix: 모든 db 관련 정보 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MaploadDialogFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MiniMapDialogFragment.kt
GoodNews/app/src/main/res/layout/fragment_mapload_dialog.xml
GoodNews/app/src/main/res/layout/fragment_minimap_dialog.xml

로드 다이얼로그 및 미니맵 레이아웃 병합
- 미니맵 레이아웃 수정
- 지도 이동 다이얼로그 추가

feat: 로드 다이얼로그 및 미니맵 레이아웃 병합

---

FE-WEB/good-news/src/common/style/GlobalStyles.tsx
FE-WEB/good-news/src/components/home/MainIntro.tsx
FE-WEB/good-news/src/pages/HomePage.tsx

- 모바일에서 풀페이지 스크롤 삭제 및 스크롤 추가
- 반응형 사이즈 변경 및 불필요 주석 제거

fix: develop-fe fullpage 오류 수정

---

GoodNews/app/src/main/AndroidManifest.xml
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/MapAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyPlaceAddEditFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSync.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSyncWorker.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/SyncService.kt

- family place, emergency place 관련 동기화 오류 수정 ( 예외 처리, db 수정)
- family fragment에서 비동기로 인해 리스트가 뜨지 않는 문제 해결

fix : family place sync,emergency place sync, family fragment error

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MapFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MiniMapDialogFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/mypage/MyPageFragment.kt
GoodNews/app/src/main/res/layout/fragment_minimap_dialog.xml
GoodNews/app/src/main/res/layout/fragment_my_page.xml

feat: 미니맵 초기 설정 완료(마이페이지에서 임시 테스트)

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MiniMapDialogFragment.kt

미니맵 프래그먼트 Destroy 시, 사용자 및 다른 사용자 지도에서 마커 삭제 처리

fix: 미니맵 프래그먼트 Destroy 시, 마커 삭제 처리

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MapDownloader.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MapFragment.kt

다운로드 중인 지도에 접근하려 해서 지도 프래그먼트 오류 발생 -> 서버에서 받은 지도 렌더링 조건 구체화하여 오류 해결

fix: 서버에서 받은 지도 렌더링 조건 구체화

---

BE-WEB/member/src/main/java/com/goodnews/member/member/service/FamilyService.java

- 가족 정보 조회 시 00초일 때 string parse 오류 해결

fix: 00초 예외 수정

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/adapter/BleAdvertiseAdapter.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/adapter/BleConnectedAdapter.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/main/MainActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MaploadDialogFragment.kt

- minimap 다이얼로그 오류 코드 변경
- mapload 다이얼로그 닫기 버튼 클릭 시, homefragment로 이동

Fix: 다이얼로그 수정 및 네비게이션 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/adapter/BleAdvertiseAdapter.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/map/MapFragment.kt
GoodNews/app/src/main/res/anim/blinking_animation.xml
GoodNews/app/src/main/res/drawable/btn_danger_line.xml
GoodNews/app/src/main/res/layout/fragment_map.xml
GoodNews/app/src/main/res/layout/item_around_advertise_list.xml
GoodNews/app/src/main/res/values-night/colors.xml
GoodNews/app/src/main/res/values/colors.xml

- 연결되지 않은 사용자 위치 보기 ui 제거 및 adapter 코드 제거
- 시설 클릭 시 위험정보 버튼 추가 및 애니메이션 적용 (다이얼로그 작업 필요)

Feat: 시설 클릭 시 위험정보 버튼 추가 및 애니메이션 적용, 사용자 위치보기 ui 제거

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/main/MainActivity.kt

fix: 지도 들어갈 때 이슈 발생 해결

---

BE-WEB/member/src/main/java/com/goodnews/member/member/controller/app/FamilyController.java
BE-WEB/member/src/main/java/com/goodnews/member/member/domain/FamilyPlace.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/response/family/FamilyPlaceInfoResponseDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/service/FamilyService.java

- 동기화 기준 설정을 위한 family place의 시간 정보 추가

fix:family place 시간 추가

---

BE-WEB/member/src/main/java/com/goodnews/member/member/domain/FamilyPlace.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/request/family/FamilyPlaceCanuseDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/request/family/FamilyPlaceUpdateRequestDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/request/family/FamilyRegistPlaceRequestDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/response/family/FamilyPlaceDetailResponseDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/service/FamilyService.java

- 알림을 줄 때 변경한 사람의 정보를 확인하기 위해서 가족 장소 관련 로직 수정

feat:family place user 정보 추가

---

GoodNews/.gitignore
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyData.kt

fix:api 수정

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyData.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/models/FamilyPlace.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSync.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/TimeService.kt

- 가족 장소 추가 시 등록 이름 저장에 따른 로직 변경
- 동기화 시 중복 저장 로직 변경

fix : 가족 장소 관련 로직 변경

---

BE-WEB/member/src/main/java/com/goodnews/member/member/controller/app/FamilyController.java
BE-WEB/member/src/main/java/com/goodnews/member/member/domain/FamilyPlace.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/request/family/FamilyPlaceCanuseDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/request/family/FamilyPlaceUpdateRequestDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/request/family/FamilyRegistPlaceRequestDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/response/family/FamilyPlaceDetailResponseDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/response/family/FamilyPlaceInfoResponseDto.java
BE-WEB/member/src/main/java/com/goodnews/member/member/service/FamilyService.java

- family place 관련 api 변경
1) 저장한 유저 정보 추가
2) 동기화 시점 설정을 위한 시간 추가

fix : family place 관련 로직 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyPlaceAddEditFragment.kt

fix:familyplace

---

GoodNews/app/src/main/AndroidManifest.xml
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyData.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyListAdapter.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSync.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSyncWorker.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/TimeService.kt

- 기존 삭제 방식에서 업데이트 방식으로 모두 변경
- 특정 경우에서 알림을 추가함
- 가족이 새로 추가된 경우
- 가족 장소의 일부 데이터가 변경 또는 추가된 경우
- 가족 멤버 리스트의 중복 추가 문제 해결

fix:family place, family member 로직 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/authority/AuthorityActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyListAdapter.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyPlaceAddEditFragment.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSync.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/SyncService.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/TimeService.kt

- 가족 신청 승인 시 리스트가 바로 업데이트 되지 않는 문제 해결
- 가족 리스트가 중복 추가 되는 경우 수정 (observer 분리)
- 가족 recycler view 최적화

fix: 가족 신청 승인 시 리스트 업데이트 로직 수정

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSync.kt

- 서버에서 받은 많은 정보를 한번에 업데이트 해야 할 경우 앱이 터지는 문제 발생
- realm update 시 transaction 오류로 인한 문제임을 확인함.
-> 따라서, realm 저장 로직과 서버에서 데이터를 받아오는 로직을 분리함.
- 분리한 결과 transaction 오류는 해결하였으나 UI 화면에 띄워지지 않는 비동기 문제 발생
- count 변수를 따로 두어 정상적으로 값이 모두 수신되었을 경우 저장 로직을 실행하도록 변경하여 해결

fix : realm transaction 오류 해결

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/adapter/BleConnectedAdapter.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/chatting/ChattingDetailActivity.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/chatting/OneChattingAdapter.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/chatting/OneChattingFragment.kt

Reverts rileyleee/GoodNews#98
머지 취소

Revert "Be/app minimap"

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSync.kt

- 알람에 저장되는 날짜 수정 및 동기화 기준 시간 변경

fix : alert 날짜 및 동기화 시간 수정

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/sync/DataSync.kt

- 장소 등록 알림 추가
- 장소 등록 시 id에 들어가는 시간 변경

feat : 장소 등록 알람 추가 및 시간 변경

---

BE-WEB/member/src/main/java/com/goodnews/member/member/controller/app/FamilyController.java
BE-WEB/member/src/main/java/com/goodnews/member/member/domain/FamilyPlace.java
BE-WEB/member/src/main/java/com/goodnews/member/member/dto/request/family/FamilyPlaceUpdateRequestDto.java

- address 수정 부분에서 address 변경이 빠져서 추가함.

fix: address 수정 누락 추가

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyData.kt

- 가족 장소 변경 시 address 변경이 누락되어 추가함.

fix: address 누락 추가

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyData.kt

fix: familyapi register누락

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyAPI.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/FamilyData.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/api/MemberData.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/ble/message/ChatDatabaseManager.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/models/FamilyMemInfo.kt
GoodNews/app/src/main/java/com/saveurlife/goodnews/models/Member.kt

refactor : familyid 자료형 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyPlaceAddEditFragment.kt

Fe/app familyplace 장소 사용여부 토글

---

BE-WEB/member/src/main/java/com/goodnews/member/common/exception/validator/FamilyValidator.java
BE-WEB/member/src/main/java/com/goodnews/member/member/controller/app/FamilyController.java
BE-WEB/member/src/main/java/com/goodnews/member/member/controller/app/MemberAppController.java
BE-WEB/member/src/main/java/com/goodnews/member/member/domain/FamilyMember.java
BE-WEB/member/src/main/java/com/goodnews/member/member/service/FamilyService.java
BE-WEB/member/src/main/java/com/goodnews/member/member/service/MemberService.java

feat : 가족 탈퇴, 회원 탈퇴, 장소 삭제 기능 추가

---

BE-WEB/member/src/main/java/com/goodnews/member/member/service/FamilyService.java

- 가족 수락 요청 시 보낸 사람의 이름이 들어가도록 수정

fix: 가족 수락 요청 이름 변경

---

GoodNews/app/src/main/java/com/saveurlife/goodnews/family/FamilyListAdapter.kt

fix: recyclerview 순서 변경
